# https://taskfile.dev
version: '3'

tasks:
  test:
    cmds:
      - pipenv run coverage run -m unittest discover -v
      - pipenv run coverage xml

  lint:
    cmds:
      - pipenv run flake8 examples src tests
      - pipenv run isort --check-only --diff examples src tests
      - pipenv run black --check --diff examples src tests
      - pipenv run mypy src tests
